name: Manual Unzip and Push to Repo

on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: 'Nama file ZIP yang ingin diekstrak (contoh: fileku.zip)'
        required: true
        default: 'file.zip'

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip file
        run: |
          mkdir -p extracted_files
          unzip "${{ github.event.inputs.zip_filename }}" -d extracted_files

      - name: Setup Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push extracted files
        run: |
          git checkout -b unzipped-files || git checkout unzipped-files
          mkdir -p extracted_output
          cp -r extracted_files/* extracted_output/

          git add extracted_output/
          git commit -m "Add extracted files from ${{ github.event.inputs.zip_filename }}" || echo "Nothing to commit"
          git push origin HEAD
