name: Manual Unzip File

on:
  workflow_dispatch:  # Trigger manual

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip file.zip to extracted_files directory
        run: |
          mkdir -p extracted_files
          unzip file.zip -d extracted_files

      - name: List extracted files
        run: ls -R extracted_files
