name: 3

on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: 'Nama file ZIP yang ingin diekstrak (contoh: fileku.zip)'
        required: true
        default: 'file.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Buat direktori untuk hasil ekstraksi
        run: mkdir -p extracted_files

      - name: Unzip file berdasarkan input
        run: |
          echo "Ekstrak file: ${{ github.event.inputs.zip_filename }}"
          unzip "${{ github.event.inputs.zip_filename }}" -d extracted_files

      - name: Tampilkan isi direktori hasil ekstraksi
        run: ls -R extracted_files

      - name: Upload hasil ekstraksi sebagai artifact
        uses: actions/upload-artifact@v3
        with:
          name: hasil-ekstraksi
          path: extracted_files/
