name: Unzip and Commit to Repo

on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: 'Nama file ZIP yang ingin diekstrak (contoh: file.zip)'
        required: true
        default: 'file.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Gunakan versi terbaru

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip the file
        run: |
          echo "Unzipping ${{ github.event.inputs.zip_filename }}"
          unzip "${{ github.event.inputs.zip_filename }}" -d extracted_output

      - name: Commit and push extracted files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Tambahkan file hasil unzip
          git add extracted_output

          # Commit jika ada perubahan
          git diff --cached --quiet || git commit -m "Unzipped ${{ github.event.inputs.zip_filename }}"

          # Push ke branch yang sedang berjalan
          git push origin HEAD
